import { t } from 'elysia';
import { idSchema } from '@SharedKernel/schemas/schemas';

export const updateStudentProfileSchema = t.Object({
	currentPassword: t.String({ minLength: 1 }),
	academicId: t.Optional(t.String({ minLength: 3, example: '2026000456' })),
	courseId: t.Optional(t.Nullable(idSchema)),
	admissionYear: t.Optional(
		t.Nullable(t.Number({ minimum: 1900, maximum: 2100, example: 2025 })),
	),
	status: t.Optional(t.String({ example: 'active' })),
	birthDate: t.Optional(t.Nullable(t.Date())),
	gender: t.Optional(t.Nullable(t.String())),
	genderIdentity: t.Optional(t.Nullable(t.String())),
	sexualOrientation: t.Optional(t.Nullable(t.String())),
	race: t.Optional(t.Nullable(t.String())),
	nationality: t.Optional(t.Nullable(t.String())),
	birthplace: t.Optional(t.Nullable(t.String({ pattern: '^[^/]+$' }))),
	birthCountry: t.Optional(t.Nullable(t.String())),
	maritalStatus: t.Optional(t.Nullable(t.String())),
	bloodType: t.Optional(t.Nullable(t.String())),
	disability: t.Optional(t.Nullable(t.String())),
	fatherName: t.Optional(t.Nullable(t.String())),
	motherName: t.Optional(t.Nullable(t.String())),
	postalCode: t.Optional(t.Nullable(t.String({ pattern: '^\\d{5}-?\\d{3}$' }))),
	street: t.Optional(t.Nullable(t.String())),
	addressNumber: t.Optional(t.Nullable(t.String())),
	addressComplement: t.Optional(t.Nullable(t.String())),
	neighborhood: t.Optional(t.Nullable(t.String())),
	state: t.Optional(t.Nullable(t.String({ pattern: '^[A-Z]{2}$' }))),
	city: t.Optional(t.Nullable(t.String())),
	phone: t.Optional(t.Nullable(t.String())),
	mobilePhone: t.Optional(t.Nullable(t.String())),
	familyIncomeRange: t.Optional(t.Nullable(t.String())),
});
