export const referenceAnnouncements = [
	{
		key: 'welcome',
		title: 'Boas-vindas à turma de Informática 2026',
		body: 'As 13 disciplinas estão disponíveis em Minhas disciplinas. Consulte o planejamento e organize seus estudos pela agenda.',
		audience: 'student',
		isPinned: true,
		publishedAt: '2026-08-03T07:00:00-03:00',
		expiresAt: null,
	},
	{
		key: 'projects',
		title: 'Orientações para os projetos integradores',
		body: 'Os projetos devem apresentar problema, proposta, referências e uma versão revisada após a devolutiva. Confira o prazo em cada disciplina.',
		audience: 'student',
		isPinned: false,
		publishedAt: '2026-09-08T08:00:00-03:00',
		expiresAt: '2026-09-19T23:59:59-03:00',
	},
	{
		key: 'faculty',
		title: 'Acompanhamento pedagógico da turma',
		body: 'Docentes: registrem o conteúdo ministrado e revisem as devolutivas das atividades antes da reunião pedagógica.',
		audience: 'professor',
		isPinned: false,
		publishedAt: '2026-09-09T08:00:00-03:00',
		expiresAt: null,
	},
	{
		key: 'expired',
		title: 'Inscrições para monitoria — encerradas',
		body: 'Comunicado expirado de demonstração para validar a filtragem dos avisos.',
		audience: 'student',
		isPinned: false,
		publishedAt: '2026-08-03T07:00:00-03:00',
		expiresAt: '2026-08-10T23:59:59-03:00',
	},
	{
		key: 'draft',
		title: 'Mostra de projetos — rascunho',
		body: 'Comunicado ainda não publicado; não deve aparecer para estudantes.',
		audience: 'student',
		isPinned: false,
		publishedAt: null,
		expiresAt: null,
	},
] as const;
