export type ReferenceSubject = {
	code: string;
	title: string;
	area: 'ART' | 'INF' | 'HUM' | 'LET' | 'MAT';
	professor: string;
	room: string;
	units: readonly [string, string];
	topics: readonly [string, string, string, string, string, string];
	project: string;
	resource: { title: string; url: string };
};

/** Titles transcribed from the user's 2026 class reference. Teaching content is illustrative. */
export const referenceSubjects: readonly ReferenceSubject[] = [
	{
		code: 'ART',
		title: 'Arte Educação',
		area: 'ART',
		professor: 'Clara Nascimento',
		room: 'Ateliê 01',
		units: ['Arte, cultura e identidade', 'Criação e expressão'],
		topics: [
			'Leitura de imagens',
			'Arte brasileira e diversidade',
			'Patrimônio cultural',
			'Composição visual',
			'Fotografia e narrativa',
			'Mostra de produção artística',
		],
		project: 'Exposição digital: identidades da comunidade',
		resource: {
			title: 'Acervo e exposições da Pinacoteca',
			url: 'https://pinacoteca.org.br/',
		},
	},
	{
		code: 'DESWEB',
		title: 'Design para Web',
		area: 'INF',
		professor: 'Rafael Azevedo',
		room: 'Laboratório 01',
		units: ['Fundamentos de interfaces', 'Prototipação e avaliação'],
		topics: [
			'Hierarquia visual',
			'Tipografia e cores',
			'Arquitetura da informação',
			'Interfaces responsivas',
			'Prototipação navegável',
			'Teste de usabilidade',
		],
		project: 'Protótipo acessível do portal da turma',
		resource: {
			title: 'Introdução à acessibilidade na web — W3C',
			url: 'https://www.w3.org/WAI/fundamentals/accessibility-intro/',
		},
	},
	{
		code: 'EMPINF',
		title: 'Empreendedorismo em Informática',
		area: 'INF',
		professor: 'Camila Moreira',
		room: 'Sala 201',
		units: ['Problemas e oportunidades', 'Validação de negócios'],
		topics: [
			'Empreendedorismo e impacto social',
			'Pesquisa com usuários',
			'Proposta de valor',
			'Modelo de negócio',
			'Custos e precificação',
			'Apresentação do projeto',
		],
		project: 'Plano de negócio para um serviço de tecnologia',
		resource: {
			title: 'Conteúdos de empreendedorismo — Sebrae',
			url: 'https://sebrae.com.br/',
		},
	},
	{
		code: 'FIL4',
		title: 'Filosofia IV',
		area: 'HUM',
		professor: 'André Vasconcelos',
		room: 'Sala 202',
		units: ['Ética e vida em sociedade', 'Tecnologia e pensamento crítico'],
		topics: [
			'Problemas da ética',
			'Liberdade e responsabilidade',
			'Justiça e cidadania',
			'Ciência e conhecimento',
			'Ética da tecnologia',
			'Argumentação filosófica',
		],
		project: 'Ensaio: responsabilidade no desenvolvimento de tecnologia',
		resource: {
			title: 'Biblioteca Domínio Público',
			url: 'http://www.dominiopublico.gov.br/',
		},
	},
	{
		code: 'GEO2',
		title: 'Geografia II',
		area: 'HUM',
		professor: 'Mariana Tavares',
		room: 'Sala 203',
		units: ['Território e população', 'Redes e transformações espaciais'],
		topics: [
			'Dinâmica populacional',
			'Urbanização brasileira',
			'Território e desigualdades',
			'Globalização e redes',
			'Energia e ambiente',
			'Leitura de indicadores geográficos',
		],
		project: 'Atlas digital dos indicadores do município',
		resource: {
			title: 'Dados e mapas — IBGE',
			url: 'https://www.ibge.gov.br/',
		},
	},
	{
		code: 'ING4',
		title: 'Inglês IV',
		area: 'LET',
		professor: 'Beatriz Carvalho',
		room: 'Sala de idiomas',
		units: ['Leitura em contexto tecnológico', 'Comunicação em projetos'],
		topics: [
			'Estratégias de leitura',
			'Vocabulário de informática',
			'Documentação técnica',
			'Comunicação profissional',
			'Apresentação oral',
			'Revisão de texto técnico',
		],
		project: 'Apresentação em inglês de um projeto da turma',
		resource: {
			title: 'Prática de inglês — British Council',
			url: 'https://learnenglish.britishcouncil.org/',
		},
	},
	{
		code: 'LEGINF',
		title: 'Legislação Aplicada à Informática',
		area: 'INF',
		professor: 'Daniel Freitas',
		room: 'Sala 201',
		units: ['Direitos no ambiente digital', 'Responsabilidade profissional'],
		topics: [
			'Cidadania digital',
			'Proteção de dados pessoais',
			'Direitos autorais e licenças',
			'Contratos de software',
			'Responsabilidade e segurança',
			'Análise de casos',
		],
		project: 'Estudo de caso sobre privacidade em um sistema escolar',
		resource: {
			title: 'Portal da Autoridade Nacional de Proteção de Dados',
			url: 'https://www.gov.br/anpd/pt-br',
		},
	},
	{
		code: 'ESP2',
		title: 'Língua Estrangeira - Espanhol II',
		area: 'LET',
		professor: 'Luciana Ribeiro',
		room: 'Sala de idiomas',
		units: ['Língua e diversidade cultural', 'Interação e produção'],
		topics: [
			'Leitura de textos cotidianos',
			'Diversidade latino-americana',
			'Narração de experiências',
			'Comunicação em situações de estudo',
			'Produção de texto',
			'Apresentação cultural',
		],
		project: 'Guia bilíngue de uma mostra cultural',
		resource: {
			title: 'Recursos de língua espanhola — Instituto Cervantes',
			url: 'https://cvc.cervantes.es/',
		},
	},
	{
		code: 'PORT4',
		title: 'Língua Portuguesa e Literatura IV',
		area: 'LET',
		professor: 'Helena Martins',
		room: 'Sala 202',
		units: ['Literatura e leitura crítica', 'Argumentação e autoria'],
		topics: [
			'Modernismo brasileiro',
			'Literatura contemporânea',
			'Leitura comparada',
			'Estratégias argumentativas',
			'Produção de resenha',
			'Revisão e publicação textual',
		],
		project: 'Revista digital de resenhas literárias',
		resource: {
			title: 'Biblioteca Nacional Digital',
			url: 'https://bndigital.bn.gov.br/',
		},
	},
	{
		code: 'MAT4',
		title: 'Matemática IV',
		area: 'MAT',
		professor: 'Gustavo Almeida',
		room: 'Sala 203',
		units: ['Representação e análise', 'Modelagem e tomada de decisão'],
		topics: [
			'Geometria analítica',
			'Equações e representações',
			'Análise combinatória',
			'Probabilidade',
			'Estatística descritiva',
			'Modelagem com dados',
		],
		project: 'Investigação estatística sobre hábitos de estudo',
		resource: {
			title: 'Recursos de matemática — GeoGebra',
			url: 'https://www.geogebra.org/',
		},
	},
	{
		code: 'PROGWEB2',
		title: 'Programação Web II',
		area: 'INF',
		professor: 'Pedro Machado',
		room: 'Laboratório 02',
		units: ['Aplicações web e persistência', 'Qualidade e integração'],
		topics: [
			'Requisições HTTP e APIs',
			'Rotas e validação',
			'Persistência de dados',
			'Autenticação e autorização',
			'Testes de integração',
			'Projeto de aplicação web',
		],
		project: 'Aplicação web para organizar projetos da turma',
		resource: {
			title: 'Aprenda desenvolvimento web — MDN',
			url: 'https://developer.mozilla.org/pt-BR/docs/Learn_web_development',
		},
	},
	{
		code: 'REDES',
		title: 'Redes de Computadores',
		area: 'INF',
		professor: 'Renata Oliveira',
		room: 'Laboratório de redes',
		units: ['Fundamentos de redes', 'Serviços e diagnóstico'],
		topics: [
			'Modelos de comunicação',
			'Endereçamento IPv4 e IPv6',
			'Comutação e roteamento',
			'Serviços DNS e DHCP',
			'Segurança de redes',
			'Diagnóstico de conectividade',
		],
		project: 'Projeto e documentação da rede de um laboratório',
		resource: {
			title: 'Materiais sobre redes e Internet — NIC.br',
			url: 'https://www.nic.br/',
		},
	},
	{
		code: 'SOC4',
		title: 'Sociologia IV',
		area: 'HUM',
		professor: 'Thiago Barros',
		room: 'Sala 201',
		units: ['Trabalho e sociedade', 'Cultura e participação'],
		topics: [
			'Transformações do trabalho',
			'Desigualdades sociais',
			'Cultura e identidade',
			'Mídias e sociabilidade',
			'Participação política',
			'Pesquisa sociológica',
		],
		project: 'Pesquisa sobre trabalho e tecnologia na comunidade',
		resource: {
			title: 'Indicadores sociais — Ipea',
			url: 'https://www.ipea.gov.br/',
		},
	},
];
