export const userSelect = {
	id: true,
	name: true,
	nickname: true,
	email: true,
	rg: true,
	cpf: true,
	role: true,
	status: true,
	avatarUrl: true,
	createdAt: true,
	updatedAt: true,
	deletedAt: true,
	emailVerifiedAt: true,
} as const;
