export const DEFAULT_USER_ID = 1;
export const DEFAULT_STUDENT_PROFILE_ID = 2;
export const DEFAULT_STUDENT_ACADEMIC_ID = '2026000123';
export const DEFAULT_STUDENT_ADMISSION_YEAR = 2026;
export const DEFAULT_STUDENT_STATUS = 'active';

export const DEFAULT_PROFESSOR_PROFILE_ID = 3;
export const DEFAULT_PROFESSOR_REGISTRY_CODE = 'PROF-2026-001';
export const DEFAULT_PROFESSOR_TITLE = 'Dr.';
export const DEFAULT_PROFESSOR_WORKLOAD = 40;

export const DEFAULT_STAFF_PROFILE_ID = 4;
