export const ERROR_CODES = [
	'UNPROCESSABLE_ENTITY',
	'NOT_FOUND',
	'CONFLICT',
	'UNAUTHORIZED',
	'VALIDATION',
	'FORBIDDEN',
	'BAD_REQUEST',
	'GONE',
	'INTERNAL_SERVER_ERROR',
	'UNKNOWN',
	'RATE_LIMIT_EXCEEDED',
] as const;

export type ErrorCode = (typeof ERROR_CODES)[number];
